### ISSUE TITLE
Problems when running it

### ISSUE THREAD

**Issue by diaverso** [workfloows/workfloows-tutorials#1]
If I run until "Move JSON to binary"
Everything works well or is what it seems.

https://imgur.com/a/pksT8kW

But in "Update file [GITHUB]" and "Upload file [GITHUB]"
I get this error and I can't add my name or the name of the repository.
https://imgur.com/a/ELfK2OA
https://imgur.com/a/69xH7Mb

How can I fix this error?

Code

https://pastebin.com/xmU87Fse

**Comment by workfloows** [comment]
Hello @diaverso, thanks for reporting. 

You need to fill fields `Repository Owner` and `Repository Name` in nodes "Update file [GITHUB]" and "Upload file [GITHUB]" (those are required fields). 

After that, workflow should work fine - I've just tested it and got no errors.

**Comment by diaverso** [comment]
Thanks
